name: Build Chroma Docker Image

on:
  workflow_dispatch:

# Do not grant jobs any permissions by default
permissions: {}    

jobs:
  build-chroma-image:
    runs-on: ubuntu-latest
    permissions:
      # required to read from the repo
      contents: read
      # required to obtain Google Cloud service account credentials
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GHA_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: marvin-recipes-workflow-main@prefect-org-github-actions.iam.gserviceaccount.com

      - name: Configure Google Cloud credential helper
        run: gcloud auth configure-docker --quiet us-docker.pkg.dev

      - name: Checkout chroma-core/chroma repository
        uses: actions/checkout@v2
        with:
          repository: chroma-core/chroma

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: us-docker.pkg.dev/prefect-prd-internal-tools/marvin-recipes/chroma:latest
