name: Build Chroma Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-chroma-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout chroma-core/chroma repository
      uses: actions/checkout@v2
      with:
        repository: chroma-core/chroma

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/chroma:latest
